#pragma once

#include "glyph_layout_overrides.h"

#ifndef GLYPH_EMERY_CENTER_X
#define GLYPH_EMERY_CENTER_X 99
#endif

#ifndef GLYPH_EMERY_CENTER_Y
#define GLYPH_EMERY_CENTER_Y 100
#endif

#ifndef GLYPH_EMERY_MARKER_RADIUS
#define GLYPH_EMERY_MARKER_RADIUS 69
#endif

#ifndef GLYPH_EMERY_HOUR_LEN
#define GLYPH_EMERY_HOUR_LEN 46
#endif

#ifndef GLYPH_EMERY_MINUTE_LEN
#define GLYPH_EMERY_MINUTE_LEN 68
#endif

#ifndef GLYPH_EMERY_OBS_CENTER_X
#define GLYPH_EMERY_OBS_CENTER_X 100
#endif

#ifndef GLYPH_EMERY_OBS_CENTER_Y
#define GLYPH_EMERY_OBS_CENTER_Y 93
#endif

#ifndef GLYPH_EMERY_OBS_MARKER_RADIUS
#define GLYPH_EMERY_OBS_MARKER_RADIUS 65
#endif

#ifndef GLYPH_EMERY_OBS_HOUR_LEN
#define GLYPH_EMERY_OBS_HOUR_LEN GLYPH_EMERY_HOUR_LEN
#endif

#ifndef GLYPH_EMERY_OBS_MINUTE_LEN
#define GLYPH_EMERY_OBS_MINUTE_LEN GLYPH_EMERY_MINUTE_LEN
#endif

#ifndef GLYPH_GABBRO_CENTER_X
#define GLYPH_GABBRO_CENTER_X 131
#endif

#ifndef GLYPH_GABBRO_CENTER_Y
#define GLYPH_GABBRO_CENTER_Y 128
#endif

#ifndef GLYPH_GABBRO_MARKER_RADIUS
#define GLYPH_GABBRO_MARKER_RADIUS 93
#endif

#ifndef GLYPH_GABBRO_HOUR_LEN
#define GLYPH_GABBRO_HOUR_LEN 50
#endif

#ifndef GLYPH_GABBRO_MINUTE_LEN
#define GLYPH_GABBRO_MINUTE_LEN 74
#endif

#ifndef GLYPH_HUB_FILL_RADIUS
#define GLYPH_HUB_FILL_RADIUS 2
#endif

#ifndef GLYPH_HUB_OUTLINE_WIDTH
#define GLYPH_HUB_OUTLINE_WIDTH 1
#endif

#ifndef GLYPH_ACCENT_MODE
#define GLYPH_ACCENT_MODE 0
#endif

#ifndef GLYPH_FORCE_HOUR
#define GLYPH_FORCE_HOUR (-1)
#endif

#ifndef GLYPH_FORCE_MINUTE
#define GLYPH_FORCE_MINUTE (-1)
#endif
