#pragma once

#include "round3_matrix_overrides.h"

#define GLYPH_FORCE_DATE_DEFAULT (-1)

#ifndef GLYPH_EMERY_CENTER_X
#define GLYPH_EMERY_CENTER_X 99
#endif

#ifndef GLYPH_EMERY_CENTER_Y
#define GLYPH_EMERY_CENTER_Y 103
#endif

#ifndef GLYPH_EMERY_MARKER_RADIUS
#define GLYPH_EMERY_MARKER_RADIUS 69
#endif

#ifndef GLYPH_EMERY_HOUR_LEN
#define GLYPH_EMERY_HOUR_LEN 32
#endif

#ifndef GLYPH_EMERY_MINUTE_LEN
#define GLYPH_EMERY_MINUTE_LEN 44
#endif

#ifndef GLYPH_EMERY_DATE_Y
#define GLYPH_EMERY_DATE_Y 184
#endif

#ifndef GLYPH_EMERY_OBS_CENTER_X
#define GLYPH_EMERY_OBS_CENTER_X 100
#endif

#ifndef GLYPH_EMERY_OBS_CENTER_Y
#define GLYPH_EMERY_OBS_CENTER_Y 93
#endif

#ifndef GLYPH_EMERY_OBS_MARKER_RADIUS
#define GLYPH_EMERY_OBS_MARKER_RADIUS 65
#endif

#ifndef GLYPH_EMERY_OBS_HOUR_LEN
#define GLYPH_EMERY_OBS_HOUR_LEN 39
#endif

#ifndef GLYPH_EMERY_OBS_MINUTE_LEN
#define GLYPH_EMERY_OBS_MINUTE_LEN 57
#endif

#ifndef GLYPH_EMERY_OBS_DATE_Y
#define GLYPH_EMERY_OBS_DATE_Y 170
#endif

#ifndef GLYPH_GABBRO_CENTER_X
#define GLYPH_GABBRO_CENTER_X 130
#endif

#ifndef GLYPH_GABBRO_CENTER_Y
#define GLYPH_GABBRO_CENTER_Y 128
#endif

#ifndef GLYPH_GABBRO_MARKER_RADIUS
#define GLYPH_GABBRO_MARKER_RADIUS 93
#endif

#ifndef GLYPH_GABBRO_HOUR_LEN
#define GLYPH_GABBRO_HOUR_LEN 42
#endif

#ifndef GLYPH_GABBRO_MINUTE_LEN
#define GLYPH_GABBRO_MINUTE_LEN 65
#endif

#ifndef GLYPH_GABBRO_DATE_Y
#define GLYPH_GABBRO_DATE_Y 189
#endif

#ifndef GLYPH_FORCE_SHOW_DATE
#define GLYPH_FORCE_SHOW_DATE GLYPH_FORCE_DATE_DEFAULT
#endif

#ifndef GLYPH_HUB_FILL_RADIUS
#define GLYPH_HUB_FILL_RADIUS 3
#endif

#ifndef GLYPH_HUB_OUTLINE_WIDTH
#define GLYPH_HUB_OUTLINE_WIDTH 1
#endif

#ifndef GLYPH_ACCENT_MODE
#define GLYPH_ACCENT_MODE 0
#endif
